# SPDX-FileCopyrightText: Copyright © Timo Koch
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "doc/img/*"
SPDX-FileCopyrightText = "Copyright © Timo Koch"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "README.md",
]
SPDX-FileCopyrightText = "Copyright © Timo Koch"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "**/*.json",
    "**/*.input",
    "**/*.geo",
    "**/*.msh",
]
SPDX-FileCopyrightText = "Copyright © Timo Koch"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "*.pc.in",
    "dune.module",
    "config.h.cmake",
    "doc/CMakeLists.txt",
    "doc/doxygen/CMakeLists.txt",
    "doc/doxygen/Doxylocal",
    "setup.sh",
    "reconfigure.sh",
    "requirements.txt",
    "data/requirements.txt",
    "cmake.opts",
]
SPDX-FileCopyrightText = "Copyright © Timo Koch"
SPDX-License-Identifier = "CC0-1.0"
